# SPDX-License-Identifier: Apache-2.0
# store-api mock for yaagents examples/store demo.
# stdlib only — no pip install step required.
FROM python:3.12-slim
WORKDIR /app
COPY app.py .
ENV PORT=8125
CMD ["python3", "app.py"]
