# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 AimpathyMinds

"""init_fastapi — scaffold generator for `yaagents init fastapi` (WI-1yaa.CLI-3).

Generates a minimal FastAPI starter wired to the YAAgents Profile v0.1:
  main.py        FastAPI app with @AgenticRouter.post agentic endpoint
  pyproject.toml project manifest depending on yaagents-fastapi
  routes.yaml    gateway route stub
  openapi.yaml   static OpenAPI spec (passes validate-openapi out of the box)
"""

from __future__ import annotations

import pathlib
from dataclasses import dataclass, field
from typing import Any

# ── file templates ────────────────────────────────────────────────────────────

_MAIN_PY = '''\
"""Campaign API — minimal YAAgents FastAPI starter.

Generated by ``yaagents init fastapi``. Edit freely.
Supports-YAAgents-Profile: v0.1
"""

from __future__ import annotations

from fastapi import FastAPI
from pydantic import BaseModel

from yaagents_fastapi import (
    AgenticContext,
    AgenticResponse,
    AgenticResponses,
    AgenticRouter,
)

app = FastAPI(title="Campaign API", version="0.1.0")
router = AgenticRouter(prefix="/campaigns")


class OptimizationRequest(BaseModel):
    budget_delta: float


@router.post(
    "/{campaign_id}/optimizations",
    resource="campaign-optimization",
    operation_kind="recommendation",
    mutating=False,
    responses=AgenticResponses(
        accepted=True,
        clarification_required=True,
        validation_failed=True,
    ),
)
async def optimize_campaign(
    campaign_id: str,
    body: OptimizationRequest,
    ctx: AgenticContext,
) -> AgenticResponse:
    """Recommend budget optimizations for a campaign."""
    return AgenticResponse.accepted(
        operation_id=f"opt-{campaign_id}",
        status_url=f"/campaigns/{campaign_id}/optimizations/status",
        message="Optimization queued.",
        correlation_id=ctx.correlation_id,
        request_id=ctx.request_id,
    )


app.include_router(router)
'''

_PYPROJECT_TOML = '''\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "campaign-api"
version = "0.1.0"
description = "Campaign API — YAAgents FastAPI starter"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111",
    "uvicorn[standard]>=0.29",
    "yaagents-fastapi>=0.1",
]

[project.scripts]
serve = "campaign_api.main:app"
'''

_ROUTES_YAML = '''\
# routes.yaml — yaagents gateway route stub.
# Copy this file to your gateway config and adjust as needed.
# Supports-YAAgents-Profile: v0.1
routes:
  - path: /campaigns/{campaign_id}/optimizations
    methods: [POST]
    upstream: http://localhost:8000
    x-yaagents:
      resource: campaign-optimization
      operationKind: recommendation
      deterministic: false
      mutating: false
'''

_OPENAPI_YAML = '''\
openapi: "3.1.0"
info:
  title: Campaign API
  version: "0.1.0"
  description: |
    Minimal YAAgents FastAPI starter — generated by ``yaagents init fastapi``.
    Supports-YAAgents-Profile: v0.1

paths:
  /campaigns/{campaign_id}/optimizations:
    post:
      summary: Recommend budget optimizations for a campaign
      operationId: optimize_campaign
      x-yaagents:
        resource: campaign-optimization
        operationKind: recommendation
        deterministic: false
        mutating: false
      parameters:
        - name: campaign_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [budget_delta]
              properties:
                budget_delta:
                  type: number
      responses:
        "202":
          description: Operation accepted for async processing (spec §7.3)
          content:
            application/vnd.yaagents.operation+json:
              schema:
                type: object
        "400":
          description: Agent requires clarification (spec §7.4)
          content:
            application/vnd.yaagents.clarification+json:
              schema:
                type: object
        "422":
          description: Request inputs failed validation (spec §7.5)
          content:
            application/vnd.yaagents.validation-error+json:
              schema:
                type: object
'''

_FILES: dict[str, str] = {
    "main.py": _MAIN_PY,
    "pyproject.toml": _PYPROJECT_TOML,
    "routes.yaml": _ROUTES_YAML,
    "openapi.yaml": _OPENAPI_YAML,
}


# ── result type ───────────────────────────────────────────────────────────────


@dataclass
class InitResult:
    """Outcome of a single `init fastapi` call."""

    target_dir: str
    created: list[str] = field(default_factory=list)
    error: str | None = None

    @property
    def succeeded(self) -> bool:
        return self.error is None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "target_dir": self.target_dir,
            "result": "OK" if self.succeeded else "ERROR",
        }
        if self.created:
            d["created"] = self.created
        if self.error:
            d["error"] = self.error
        return d


# ── public entry point ────────────────────────────────────────────────────────


def init_fastapi(target_dir: str, *, force: bool = False) -> InitResult:
    """Generate a minimal FastAPI starter at *target_dir*.

    Refuses to proceed if *target_dir* is non-empty unless *force* is True.
    Never raises; caller examines ``.succeeded``.
    """
    target = pathlib.Path(target_dir)

    if ".." in target.parts:
        return InitResult(target_dir=target_dir, error="path traversal not allowed")

    if target.exists() and any(target.iterdir()) and not force:
        return InitResult(
            target_dir=target_dir,
            error=(
                f"directory {str(target)!r} is non-empty; "
                "pass --force to overwrite"
            ),
        )

    target.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    for filename, content in _FILES.items():
        (target / filename).write_text(content, encoding="utf-8")
        created.append(filename)

    return InitResult(target_dir=str(target), created=created)
