// Code generated by tools/gen; DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AimpathyMinds

//go:generate go -C ../../tools/gen run . ../../sdk-go/sdkgo/types.go

package sdkgo

// Trace holds the mandatory correlation identifiers propagated from the inbound request.
type Trace struct {
	CorrelationID string `json:"correlationId"`
	RequestID     string `json:"requestId"`
}

// OperationAccepted is the body for HTTP 202 application/vnd.yaagents.operation+json.
type OperationAccepted struct {
	Type        string `json:"type"`
	Code        string `json:"code"`
	Message     string `json:"message"`
	OperationID string `json:"operationId"`
	StatusURL   string `json:"statusUrl"`
	Trace       Trace  `json:"trace"`
}

// RequiredInput describes a single input the caller must supply to proceed.
type RequiredInput struct {
	Name          string   `json:"name"`
	Location      string   `json:"location"`
	Type          string   `json:"type"`
	Required      bool     `json:"required"`
	Question      string   `json:"question"`
	AllowedValues []string `json:"allowedValues,omitempty"`
}

// ClarificationRequiredBody is the body for HTTP 400 application/vnd.yaagents.clarification+json.
type ClarificationRequiredBody struct {
	Type           string          `json:"type"`
	Code           string          `json:"code"`
	Message        string          `json:"message"`
	RequiredInputs []RequiredInput `json:"requiredInputs"`
	Trace          Trace           `json:"trace"`
}

// ValidationError describes a single field-level validation error.
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ValidationFailedBody is the body for HTTP 422 application/vnd.yaagents.validation-error+json.
type ValidationFailedBody struct {
	Type    string            `json:"type"`
	Code    string            `json:"code"`
	Message string            `json:"message"`
	Errors  []ValidationError `json:"errors,omitempty"`
	Trace   Trace             `json:"trace"`
}

// ApprovalRequiredBody is the body for HTTP 412 application/vnd.yaagents.approval-required+json.
type ApprovalRequiredBody struct {
	Type          string `json:"type"`
	Code          string `json:"code"`
	Message       string `json:"message"`
	ApprovalToken string `json:"approvalToken"`
	Trace         Trace  `json:"trace"`
}

// ConflictBody is the body for HTTP 409 application/vnd.yaagents.conflict+json.
type ConflictBody struct {
	Type                  string `json:"type"`
	Code                  string `json:"code"`
	Message               string `json:"message"`
	ConflictingResourceID string `json:"conflictingResourceId,omitempty"`
	Trace                 Trace  `json:"trace"`
}

// AgenticErrorBody is the body for HTTP 403/424/500 application/vnd.yaagents.error+json.
type AgenticErrorBody struct {
	Type       string `json:"type"`
	Code       string `json:"code"`
	Message    string `json:"message"`
	RetryAfter int    `json:"retryAfter,omitempty"`
	Trace      Trace  `json:"trace"`
}
